# Configuration for probot-auto-labeler - https://github.com/probot/autolabeler

# label: file | path
iOS: ["/flutter_inappwebview_ios", "*.dart", "*.swift", "*.h", "*.m", "*.plist", "*.storyboard", "*.xcconfig", Podfile*"]
macOS: ["/flutter_inappwebview_macos", "*.dart", "*.swift", "*.h", "*.m", "*.plist", "*.storyboard", "*.xcconfig", Podfile*"]
platform_interface: ["/flutter_inappwebview_platform_interface", "*.dart"]
plugin: ["/flutter_inappwebview", "*.dart"]
documentation: ["*.md"]
legal: ["LICENSE*", "NOTICES*"]
